title: Tshifhumulo Mapasa
#logo: ![WhatsApp Image 2023-08-19 at 10 34 03](https://github.com/Tshifhumulo10/Portfolio/assets/115041717/fa13a03a-00e3-4d49-a087-25a1b7061c2d)
description: Data Analyst| Data Scientist| BI Analyst
#show_downloads: true
theme: jekyll-theme-minimal
